version: '3.4'

services:

  animation-host:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /projects/AROSS/Animations:/usr/share/nginx/html:ro
      - ./file_server/default.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    restart: on-failure
