version: 2

setup: &setup
  working_directory: ~/ros-animator-widget

jobs:
  test:
    <<: *setup
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
  build:
    <<: *setup
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Build Bundle
          command: npm run build
      - persist_to_workspace:
          root: ~/ros-animator-widget
          paths: ./build

  publish:
    <<: *setup
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: ~/ros-animator-widget/build
      - run: 
          name: Publish
          command: ls -la .


workflows:
  version: 2

  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - publish:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: main
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(\.[\-a-zA-Z0-9]+)?$/
