version: 2

setup: &setup
  working_directory: ~/ros-animator-widget

jobs:
  test:
    <<: *setup
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test


workflows:
  version: 2

  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
